### ISSUE TITLE
Cannot change effects in EnchantGiver config

### ISSUE THREAD

**Issue by itsdinkd** [LordDeatHunter/EnchantGiver#3]
As posted here https://github.com/Noaaan/MythicMetals/issues/60
![image](https://user-images.githubusercontent.com/35115304/150694135-032cebe2-da11-43ea-9460-6c162f92acca.png)

when changing a items enchant, it reverts back to the mod specific one in the config. this is using latest enchant giver for 1.18.1

**Comment by Noaaan** [comment]
Closed in favor of issue #4.
