### ISSUE TITLE
EnchantGiver Visually Levels Up Enchantments, but According to IntelliJ, the Level is Still Whatever is Set in the Config

### ISSUE THREAD

**Issue by chronosacaria** [LordDeatHunter/EnchantGiver#5]
Upon a user doing some testing with MCDW, they found that some of the enchantments were not leveling up when using books or combining items. However, when using the commands within EnchantGiver, this does work. We did some more testing and found that this is the case with _all_ innate enchantments set via EnchantGiver. 

We also suspect that the reason for this is that in the `EnchantmentHelperMixin`, there is a point at which the return value is always set to the string value that it is in the config, though we might be misunderstanding the way that EnchantGiver is functioning. If there is anything that we can do to help with the resolution of this issue, please let Kluzzio or I know and we'll be as helpful as we can be.

Kluzzio thinks that a potential solution to the issue could be something along the line of what is below. Please disregard the red underlining, it is because it was written where IntelliJ was throwing a fit because of it:

![snippit](https://user-images.githubusercontent.com/67794130/160857671-17af60d0-addc-4f10-84da-aa6bfb38cb99.png)

**Comment by Kluzzio** [comment]
Please forgive my write up if this is the wrong location for the code, but the general idea should stand wherever necessary to resolve this. I unfortunately did not do any testing to see if this code would work. Please let me know if you need anything from me, and thanks for your time!
